"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'comments',
    'posts',
    'contests',
    'contractapi',

    "corsheaders",
    "django_jalali",
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_yasg',
]

REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%Y/%m/%d (%H:%M:%S)",
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=5),
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.MyTokenObtainPairSerializer",
}    

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'https://mathbot.ir', 'http://localhost:3000'
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

ENV = config("ENV", default="development")

if ENV == "production":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config("MYSQL_NAME"),
            'USER': config("MYSQL_USER"),
            'PASSWORD': config("MYSQL_PASSWORD"),
            'HOST': config("MYSQL_HOST", default="localhost"),
            'PORT': config("MYSQL_PORT", default="3306"),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / config("SQLITE_NAME", default="db.sqlite3"),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

TIME_ZONE = 'Asia/Tehran'

LANGUAGE_CODE = 'fa-ir'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_DIR = BASE_DIR / 'uploads/'
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Blockchain (ContestPrize smart contract) - see docs/blockchain-integration.md
# The contract can only be used when RPC_URL and CONTRACT_ADDRESS are set.
# OWNER_PRIVATE_KEY is only needed for admin actions (create / award / refund / withdraw).

BLOCKCHAIN = {
    'RPC_URL': config('BLOCKCHAIN_RPC_URL', default=''),
    'CHAIN_ID': config('BLOCKCHAIN_CHAIN_ID', default=11155111, cast=int),  # 11155111 = Sepolia
    'CONTRACT_ADDRESS': config('CONTEST_CONTRACT_ADDRESS', default=''),
    'OWNER_PRIVATE_KEY': config('BLOCKCHAIN_OWNER_PRIVATE_KEY', default=''),
    'EXPLORER_URL': config('BLOCKCHAIN_EXPLORER_URL', default='https://sepolia.etherscan.io'),
    'RPC_TIMEOUT': config('BLOCKCHAIN_RPC_TIMEOUT', default=20, cast=int),
    'GAS_MULTIPLIER': config('BLOCKCHAIN_GAS_MULTIPLIER', default=1.2, cast=float),
}
